# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oscar Campo
email: oscampo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Imágenes para descargar, reflexionar, colorear, compartir!!.
  
  Compartir es bendecir! 
  
  La gloria sea siempre para Dios!
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_name: oscampo
twitter_username: OscarCampo_
facebooc_name: oscar.campo
github_username:  oscampo

# Build settings
markdown: kramdown
